[build]
  base = "."
  publish = "client"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[functions]]
  directory = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "client"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socket"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
